FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon
COPY . .
EXPOSE 5173
CMD ["nodemon", "--watch", "src", "--ext", "vue,js,ts,css,json,html", "--exec", "npm run dev -- --host"]
